openapi: 3.0.3
info:
  version: 1.0.0
  title: DCSA Partner Reference API
  description: |
    <h1>DCSA Partner Reference API</h1>

    This API is...

    ### API Design & Implementation Principles
    This API follows the guidelines defined in version 2.0 of the API Design & Implementation Principles which can be found on the [DCSA Developer Portal](https://developer.dcsa.org/api_design)

    ### Changelog and GitHub
    For a changelog, please click [here](https://github.com/dcsaorg/DCSA-OpenAPI/tree/master/ovs_hub_ref/v1#v100). If you have any questions, feel free to send an email to [ovshub-support@dcsa.org](mailto:ovshub-support@dcsa.org).

    API specification issued by [DCSA.org](https://dcsa.org/).
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  contact:
    name: Digital Container Shipping Association (DCSA)
    url: 'https://dcsa.org'
    email: info@dcsa.org
tags:
  - name: Partner References
    description: Mapping of partner services, voyages and transportCalls
paths:
  /v1/service-references:
    get:
      tags:
        - Partner References
      summary: |
        Get a list of partner services
      operationId: get-partner-services
      description: |
        Get a list of partner services. Since the `carrierServiceCode` is not unique across carriers - it is possible that multiple response objects are matched when making a request. If a service from a specific carrier is wanted - the `carrierSMDGCode` can further qualify (filter) the result to only return a single object.

        If `universalServiceReference` is used - it is not needed to qualify the request with a `carrierSMDGCode` as the `universalServiceReference` is unique across carriers.

        If a service is matched, the response will contain all linked partner services as part of that response object.

        **Note:** When using the filters it is possible to apply mutually exclusive values: e.g. a `carrierServiceCode` and a `universalServiceReference` that are not linked/related. In this case the response is an empty list: `[]` (it is **not** an error).

        **Condition:** It is mandatory to provide either `carrierServiceCode` or `universalServiceReference` or both when using this endpoint.
      parameters:
        - name: carrierServiceCode
          in: query
          required: false
          description: |
            The carrier specific service code to fetch partner service codes for. The result will include all known partner service codes.
            
            **Condition:** It is mandatory to provide either `carrierServiceCode` or `universalServiceReference` or both
          schema:
            type: string
            maxLength: 11
            example: FE1
        - name: universalServiceReference
          in: query
          required: false
          description: |
            The Universal Service Reference (USR) as defined by DCSA to filter by. The result will include all known partner service codes linked/related to the USR.
            
            **Condition:** It is mandatory to provide either `carrierServiceCode` or `universalServiceReference` or both
          schema:
            type: string
            pattern: ^SR\d{5}[A-Z]$
            maxLength: 8
            minLength: 8
            example: SR12345A
        - name: carrierSMDGCode
          in: query
          required: false
          description: |
            The carrier specific `SMDG` code related to the `carrierServiceCode` path parameter. The result will be filtered to only include `carrierServiceCode` from the specified `carrierSMDGCode` (along with any linked/related partner `carrierServiceCodes`).
          schema:
            type: string
            maxLength: 10
            example: MSK
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PartnerService'
              examples:
                servicesExample:
                  summary: |
                    Returning a service with 2 linked VSA partner services
                  description: |
                    Making the following request:
                    
                        GET /v1/service-references?carrierServiceCode=FE1
                    Gets a list of partner services for `carrierServiceCode='FE1'`. In this example the service is connected to `universalServiceReference='SR00112X'`. In addition to the `carrierServiceCode` requested - a `carrierServiceCode` from Evergreen is also provided.
                  value:
                    - universalServiceReference: SR00112X
                      servicePartners:
                        - carrierSMDGCode: MSK
                          carrierServiceName: Great Lion service
                          carrierServiceCode: FE1
                        - carrierSMDGCode: EMC
                          carrierServiceName: Dragon express
                          carrierServiceCode: DR01
                multipleServicesExample:
                  summary: |
                    Returning multiple services matching the same service code
                  description: |
                    Making the following request:
                    
                        GET /v1/service-references?carrierServiceCode=878
                    Gets a list of partner services for `carrierServiceCode='878'`. In this example the service matches services in both YML and HPL. Each of the services are linked to partner services. Only the first matched service also has a `universalServiceReference`.

                    If only the service from HPL was needed - then the `carrierServiceCode` query parameter should have been used in addition to `carrierSMDGCode`. E.g.

                        GET /v1/service-references?carrierServiceCode=878&carrierSMDGCode=HPL
                  value:
                    - universalServiceReference: SR54321X
                      servicePartners:
                        - carrierSMDGCode: YML
                          carrierServiceName: Trans Pacific Service
                          carrierServiceCode: '878'
                        - carrierSMDGCode: EMC
                          carrierServiceName: Asia Express
                          carrierServiceCode: A01
                    - servicePartners:
                        - carrierSMDGCode: HPL
                          carrierServiceName: Europe 1
                          carrierServiceCode: '878'
                        - carrierSMDGCode: MSK
                          carrierServiceName: Viking
                          carrierServiceCode: MM1
                        - carrierSMDGCode: ZIM
                          carrierServiceName: Euro Express
                          carrierServiceCode: ZOK
          headers:
            API-Version:
              $ref: '#/components/headers/API-Version'
        '400':
          description: Bad Request
          headers:
            API-Version:
              schema:
                type: string
                example: 1.0.0
              description: |
                SemVer used to indicate the version of the contract (API version) returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Example 1:
                  value:
                    httpMethod: GET
                    requestUri: /v1/service-references?carrierServiceCodeX=FE1
                    statusCode: 400
                    statusCodeText: Bad Request
                    providerCorrelationReference: 4426d965-0dd8-4005-8c63-dc68b01c4962
                    errorDateTime: 2019-11-12T07:41:00+08:30
                    errors:
                      - errorCode: 7007
                        errorCodeText: invalidQuery
                        errorCodeMessage: Unknown carrierServiceCodeX query parameter
        '500':
          description: Internal Server Error
          headers:
            API-Version:
              schema:
                type: string
                example: 1.0.0
              description: |
                SemVer used to indicate the version of the contract (API version) returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Example 1:
                  value:
                    httpMethod: GET
                    requestUri: /v1/service-references?carrierServiceCode=FE1
                    statusCode: 500
                    statusCodeText: Internal Server Error
                    statusCodeMessage: Cannot process request.
                    providerCorrelationReference: 4426d965-0dd8-4005-8c63-dc68b01c4962
                    errorDateTime: 2019-11-12T07:41:00+08:30
                    errors:
                      - errorCode: 7003
                        errorCodeText: Internal Server Error
                        errorCodeMessage: An internal error occurred.

  /v1/voyage-references:
    get:
      tags:
        - Partner References
      summary: |
        Get a list of partner Voyages
      operationId: get-partner-voyages
      description: |
        Get a list of partner voyages and their service. When calling this endpoint it is mandatory to provide a service and a voyage. The service MUST be provided using the `carrierServiceCode` or `universalServiceReference` (or both). At least one of the following voyage filters MUST be provided: `carrierImportVoyageNumber`, `carrierExportVoyageNumber`, `universalImportVoyageReference` or `universalExportVoyageReference`.

        If the carrier specific query parameters are used (`carrierServiceCode`, `carrierImportVoyageNumber` and `carrierExportVoyageNumber`) it is possible to further filter the response using the `carrierSMDGCode`.

        If a voyage is matched, all partner voyages and service information is included per object in the response. The response is grouped per service.

        **Note:** When using the filters it is possible to apply mutually exclusive values: e.g. a `carrierServiceCode` and a `carrierImportVoyageNumber` that are not linked/related. In this case the response is an empty list: `[]` (it is **not** an error).

        **Condition:** It is mandatory to provide:
          - `carrierServiceCode` or `universalServiceReference` or both
          - `carrierImportVoyageNumber`, `carrierExportVoyageNumber`, `universalImportVoyageReference` or `universalExportVoyageReference` or combinations
      parameters:
        - name: carrierServiceCode
          in: query
          required: false
          description: |
            The carrier specific service code to filter by. The result will only include voyages linked to the specified `carrierServiceCode`.
            
            **Condition:** It is mandatory to provide either `carrierServiceCode` or `universalServiceReference` or both when using this endpoint.
          schema:
            type: string
            maxLength: 11
            example: FE1
        - name: universalServiceReference
          in: query
          required: false
          description: |
            The Universal Service Reference (USR) as defined by DCSA to filter by. The result will only include voyages linked to the specified `universalServiceReference`.
            
            **Condition:** It is mandatory to provide either `carrierServiceCode` or `universalServiceReference` or both when using this endpoint.
          schema:
            type: string
            pattern: ^SR\d{5}[A-Z]$
            maxLength: 8
            minLength: 8
            example: SR12345A
        - name: carrierImportVoyageNumber
          in: query
          required: false
          description: |
            The carrier specific import voyage number to filter by. The result will only return voyages including the import voyage number.
            
            **Condition:** It is mandatory to provide either `carrierImportVoyageNumber`, `carrierExportVoyageNumber`, `universalImportVoyageReference` or `universalExportVoyageReference` or any combination.
          schema:
            type: string
            maxLength: 50
            pattern: ^\S(?:.*\S)?$
            example: 2103N
        - name: carrierExportVoyageNumber
          in: query
          required: false
          description: |
            The carrier specific export voyage number to filter by. The result will only return voyages including the export voyage number.
            
            **Condition:** It is mandatory to provide either `carrierImportVoyageNumber`, `carrierExportVoyageNumber`, `universalImportVoyageReference` or `universalExportVoyageReference` or any combination.
          schema:
            type: string
            maxLength: 50
            pattern: ^\S(?:.*\S)?$
            example: 2103N
        - name: universalImportVoyageReference
          in: query
          description: |
            The Universal Reference of an import voyage. The result will only return partner voyages including the `universalImportVoyageReference`.
            
            **Condition:** It is mandatory to provide either `carrierImportVoyageNumber`, `carrierExportVoyageNumber`, `universalImportVoyageReference` or `universalExportVoyageReference` or any combination.
          schema:
            type: string
            pattern: ^\d{2}[0-9A-Z]{2}[NEWSR]$
            maxLength: 5
            example: 2201N
        - name: universalExportVoyageReference
          in: query
          description: |
            The Universal Reference of an export voyage. The result will only return partner voyages including the `universalExportVoyageReference`.
            
            **Condition:** It is mandatory to provide either `carrierImportVoyageNumber`, `carrierExportVoyageNumber`, `universalImportVoyageReference` or `universalExportVoyageReference` or any combination.
          schema:
            type: string
            pattern: ^\d{2}[0-9A-Z]{2}[NEWSR]$
            maxLength: 5
            example: 2201N
        - name: carrierSMDGCode
          in: query
          required: false
          description: |
            The carrier specific SMDG code related to the `carrierServiceCode`, `carrierImportVoyageNumber` or `carrierExportVoyageNumber` query parameter. The result will be filtered to only include `carrierServiceCode` from the specified `carrierSMDGCode`.
          schema:
            type: string
            maxLength: 10
            example: EMC
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PartnerVoyage'
              examples:
                voyagesExample:
                  summary: |
                    Returning a list of voyages with linked services
                  description: |
                    Making the following request:

                        GET /v1/voyage-references?universalServiceReference=SR00112X&carrierImportVoyageNumber=2602N
                    Gets a list of partner voyages for `carrierImportVoyageNumber='2602N'` connected to `universalServiceReference='SR00112X'`.

                    The matched `carrierImportVoyageNumber` is linked to a VSA partner (YML) using a different voyage number.
                  value:
                    - universalServiceReference: SR00112X
                      universalImportVoyageReference: 2602N
                      universalExportVoyageReference: 2602N
                      carrierVoyages:
                        - carrierSMDGCode: MSK
                          carrierServiceName: Great Lion service
                          carrierServiceCode: '123'
                          carrierImportVoyageNumber: 2602N
                          carrierExportVoyageNumber: 2602N
                        - carrierSMDGCode: YML
                          carrierServiceName: EuroAsia
                          carrierServiceCode: XYZ
                          carrierImportVoyageNumber: N200
          headers:
            API-Version:
              $ref: '#/components/headers/API-Version'
        '400':
          description: Bad Request
          headers:
            API-Version:
              schema:
                type: string
                example: 1.0.0
              description: |
                SemVer used to indicate the version of the contract (API version) returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Example 1:
                  value:
                    httpMethod: GET
                    requestUri: /v1/voyage-references?carrierImportVoyageNumber=2602N
                    statusCode: 400
                    statusCodeText: Bad Request
                    providerCorrelationReference: 4426d965-0dd8-4005-8c63-dc68b01c4962
                    errorDateTime: 2019-11-12T07:41:00+08:30
                    errors:
                      - errorCode: 7007
                        errorCodeText: invalidQuery
                        errorCodeMessage: It is mandatory to provide a service filter
        '500':
          description: Internal Server Error
          headers:
            API-Version:
              schema:
                type: string
                example: 1.0.0
              description: |
                SemVer used to indicate the version of the contract (API version) returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Example 1:
                  value:
                    httpMethod: GET
                    requestUri: /v1/voyage-references?universalServiceReference=SR00112X&carrierImportVoyageNumber=2602N
                    statusCode: 500
                    statusCodeText: Internal Server Error
                    statusCodeMessage: Cannot process request.
                    providerCorrelationReference: 4426d965-0dd8-4005-8c63-dc68b01c4962
                    errorDateTime: 2019-11-12T07:41:00+08:30
                    errors:
                      - errorCode: 7003
                        errorCodeText: Internal Server Error
                        errorCodeMessage: An internal error occurred.

  /v1/transport-call-references/{transportCallReference}:
    get:
      tags:
        - Partner References
      summary: |
        Get a list of partner TransportCalls
      operationId: get-partner-transport-calls
      description: |
        Get a list of partner **TransportCalls** linked with voyage(s) and service(s) matching the provided `transportCallReference`.

        In some rare cases a `transportCallReference` is different between partners. This endpoint lists all known TransportCalls for a given `transportCallReference`. If a `transportCallReference` is reused between services it is possible to filter the response to match a particular service (this can be via `carrierServiceCode` or `universalServiceReference`).

        `carrierSMDGCode` filter can be used to better identify the `carrierServiceCode` filter (if it is used). It can also be used to identify the `transportCallReference`.

        If a TransportCall is matched, all known `transportCallReferences` along with partner `transportCallReferences` are returned together with the voyage and service information for partners. The response is grouped per service.

        **Note:** When using the filters it is possible to apply mutually exclusive values: e.g. a `carrierServiceCode` and a `transportCallReference` that are not linked/related. In this case the response is an empty list: `[]` (it is **not** an error).
      parameters:
        - name: transportCallReference
          in: path
          required: true
          description: |
            The transportCall to filter by. The result will only return TransportCalls including the TransportCallReference.
          schema:
            type: string
            maxLength: 100
            example: SR11111X-9321483-2107W-NLRTM-HPD2-1-1
        - name: carrierSMDGCode
          in: query
          required: false
          description: |
            The carrier specific SMDG code. It can be used to filter the result in case a `transportCallReference` is used by many carriers. The result will be filtered to only include `transportCallReference` from the specified `carrierSMDGCode`.
          schema:
            type: string
            maxLength: 10
            example: MSK
        - name: carrierServiceCode
          in: query
          required: false
          description: |
            The carrier specific service code to filter by.
          schema:
            type: string
            maxLength: 11
            example: FE1
        - name: universalServiceReference
          in: query
          required: false
          description: |
            The Universal Service Reference (USR) as defined by DCSA to filter by.
          schema:
            type: string
            pattern: ^SR\d{5}[A-Z]$
            maxLength: 8
            minLength: 8
            example: SR12345A
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PartnerTransportCall'
              examples:
                transportCallExample:
                  summary: |
                    Returning a list of partner transportCallReferences
                  description: |
                    Making the following request:

                        GET /v1/transport-call-references/SR00648D-123456-2095-818B-CNXMN-XHCT-1-1
                    Gets a list of partner TransportCalls for `transportCallReference='SR00648D-123456-2095-818B-CNXMN-XHCT-1-1'`. In the example, the matched `transportCallReference` by `HPL` is no longer valid (expired on the 24th of Dec 2025), a newer `transportCallReference` exists. YML and MSK partner TransportCalls are also listed. All are listed in the response

                    The matched `transportCallReference` is also used by YML, MSK uses a different `transportCallReference`.
                  value:
                    - universalServiceReference: SR00400X
                      universalImportVoyageReference: 2603N
                      universalExportVoyageReference: 2603N
                      carrierTransportCalls:
                        - carrierSMDGCode: HPL
                          carrierServiceName: Asia East West
                          carrierServiceCode: '333'
                          carrierImportVoyageNumber: 2603N
                          carrierExportVoyageNumber: 2603N
                          transportCallReferences:
                            - transportCallReference: 'SR00648D-123456-2095-818B-CNXMN-XHCT-1-1'
                              validUntilDateTime: '2025-12-24T18:00:00Z'
                            - transportCallReference: 'SR00648D-123456-2095-818B-CNXMN-XHCT-2-1'
                              validUntilDateTime: '2026-01-10T00:00:00Z'
                            - transportCallReference: 'SR00648D-123456-2095-818B-CNXMN-XHCT-3-1'
                              validUntilDateTime: '2026-03-10T00:00:00Z'
                            - transportCallReference: 'SR00648D-123456-2095-818B-CNXMN-XHCT-4-1'
                        - carrierSMDGCode: YML
                          carrierServiceName: EuroAsia
                          carrierServiceCode: XYZ
                          carrierImportVoyageNumber: N200
                          transportCallReferences:
                            - transportCallReference: 'SR00648D-123456-2095-818B-CNXMN-XHCT-4-1'
                        - carrierSMDGCode: MSK
                          carrierServiceName: Great Lion Service
                          carrierServiceCode: '123'
                          carrierImportVoyageNumber: N120
                          transportCallReferences:
                            - transportCallReference: 'MSK123'
          headers:
            API-Version:
              $ref: '#/components/headers/API-Version'
        '400':
          description: Bad Request
          headers:
            API-Version:
              schema:
                type: string
                example: 1.0.0
              description: |
                SemVer used to indicate the version of the contract (API version) returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Example 1:
                  value:
                    httpMethod: GET
                    requestUri: /v1/transport-call-references/SR11111X-9321483-2107W-NLAMS-ACT-1-1
                    statusCode: 400
                    statusCodeText: Bad Request
                    providerCorrelationReference: 4426d965-0dd8-4005-8c63-dc68b01c4962
                    errorDateTime: 2019-11-12T07:41:00+08:30
                    errors:
                      - errorCode: 7007
                        errorCodeText: invalidQuery
                        errorCodeMessage: Unknown transportCallReference
        '500':
          description: Internal Server Error
          headers:
            API-Version:
              schema:
                type: string
                example: 1.0.0
              description: |
                SemVer used to indicate the version of the contract (API version) returned.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Example 1:
                  value:
                    httpMethod: GET
                    requestUri: /v1/transport-call-references/SR11111X-9321483-2107W-NLAMS-ACT-1-1
                    statusCode: 500
                    statusCodeText: Internal Server Error
                    statusCodeMessage: Cannot process request.
                    providerCorrelationReference: 4426d965-0dd8-4005-8c63-dc68b01c4962
                    errorDateTime: 2019-11-12T07:41:00+08:30
                    errors:
                      - errorCode: 7003
                        errorCodeText: Internal Server Error
                        errorCodeMessage: An internal error occurred.

components:
  headers:
    API-Version:
      schema:
        type: string
        example: 1.0.0
      description: |
        SemVer used to indicate the version of the contract (API version) returned.
      required: true
  schemas:
    ErrorResponse:
      title: Error Response
      type: object
      description: Unexpected error
      properties:
        httpMethod:
          description: |
            The HTTP method used to make the request e.g. `GET`, `POST`, etc
          type: string
          example: POST
          enum:
            - GET
            - HEAD
            - POST
            - PUT
            - DELETE
            - OPTIONS
            - PATCH
        requestUri:
          description: |
            The URI that was requested.
          type: string
          example: /v1/events
        statusCode:
          description: |
            The HTTP status code returned.
          type: integer
          format: int32
          example: 400
        statusCodeText:
          description: |
            A standard short description corresponding to the HTTP status code.
          type: string
          maxLength: 50
          example: Bad Request
        statusCodeMessage:
          description: |
            A long description corresponding to the HTTP status code with additional information.
          type: string
          maxLength: 200
          example: The supplied data could not be accepted
        providerCorrelationReference:
          description: |
            A unique identifier to the HTTP request within the scope of the API provider.
          type: string
          maxLength: 100
          example: 4426d965-0dd8-4005-8c63-dc68b01c4962
        errorDateTime:
          description: |
            The DateTime corresponding to the error occurring.
          type: string
          format: date-time
          example: '2024-09-04T09:41:00Z'
        errors:
          type: array
          description: |
            An array of errors providing more detail about the root cause.
          minItems: 1
          items:
            $ref: '#/components/schemas/DetailedError'
      required:
        - httpMethod
        - requestUri
        - statusCode
        - statusCodeText
        - errorDateTime
        - errors
    DetailedError:
      type: object
      title: Detailed Error
      description: |
        A detailed description of what has caused the error.
      properties:
        errorCode:
          type: integer
          format: int32
          description: |
            The detailed error code returned. The codes returned are maintained by the implementor of the API. For further explanation as to the meaning of an errorCode please consult the implementer.

            **Note:** Previously it was the intention of DCSA to standardise this but it never gained traction.
          minimum: 7000
          maximum: 9999
          example: 7003
        property:
          type: string
          maxLength: 100
          description: |
            The name of the property causing the error.
          example: facilityCode
        value:
          type: string
          maxLength: 500
          description: |
            The value of the property causing the error serialised as a string exactly as in the original request.
          example: SG SIN WHS
        jsonPath:
          type: string
          maxLength: 500
          description: |
            A path to the property causing the error, formatted according to [JSONPath](https://github.com/json-path/JsonPath).
          example: $.location.facilityCode
        errorCodeText:
          description: |
            A standard short description corresponding to the `errorCode`.
          type: string
          maxLength: 100
          example: invalidData
        errorCodeMessage:
          type: string
          maxLength: 5000
          description: |
            A long description corresponding to the `errorCode` with additional information.
          example: Spaces not allowed in facility code
      required:
        - errorCodeText
        - errorCodeMessage
    PartnerService:
      type: object
      description: |
        Lists all known services for partners for a particular `universalServiceReference`.
      properties:
        universalServiceReference:
          type: string
          example: SR12345A
          pattern: ^SR\d{5}[A-Z]$
          maxLength: 8
          minLength: 8
          description: |
            A global unique service reference, as per DCSA standard, agreed by VSA partners for the service. The service reference must match the regular expression pattern: `SR\d{5}[A-Z]`. The letters `SR` followed by `5` digits, followed by a checksum-character as a capital letter from `A to Z`.
        servicePartners:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/ServicePartner'
      required:
        - servicePartners

    ServicePartner:
      type: object
      description: |
        An object including a carrier specific service code, service name and the SMDG code.
      properties:
        carrierSMDGCode:
          type: string
          description: |
            The carrier code based on SMDG Liner Code List.
          maxLength: 10
          example: MSK
        carrierServiceName:
          type: string
          description: The name of the service.
          maxLength: 50
          pattern: ^\S(?:.*\S)?$
          example: Great Lion Service
        carrierServiceCode:
          type: string
          description: The carrier-specific code of the service for which the schedule details are published.
          maxLength: 11
          example: FE1
          pattern: ^\S(?:.*\S)?$
      required:
        - carrierSMDGCode
        - carrierServiceCode

    PartnerVoyage:
      type: object
      description: |
        Lists universal service references and import/export voyages to carrier specific voyages and services.
      properties:
        universalServiceReference:
          type: string
          maxLength: 8
          minLength: 8
          pattern: ^SR\d{5}[A-Z]$
          description: |
            A global unique service reference, as per DCSA standard, agreed by VSA partners for the service. The service reference must match the regular expression pattern: `SR\d{5}[A-Z]`. The letters `SR` followed by `5` digits, followed by a checksum-character as a capital letter from `A to Z`.
          example: SR12345A
        universalImportVoyageReference:
          type: string
          minLength: 5
          maxLength: 5
          pattern: ^\d{2}[0-9A-Z]{2}[NEWSR]$
          description: |
            A global unique voyage reference for the import Voyage, as per DCSA standard, agreed by VSA partners for the voyage. The voyage reference must match the regular expression pattern: `\d{2}[0-9A-Z]{2}[NEWSR]`
            
            - `2 digits` for the year
            - `2 alphanumeric characters` for the sequence number of the voyage
            - `1 character` for the direction/haul (`N`orth, `E`ast, `W`est, `S`outh or `R`oundtrip).

          example: 2103N
        universalExportVoyageReference:
          type: string
          minLength: 5
          maxLength: 5
          pattern: ^\d{2}[0-9A-Z]{2}[NEWSR]$
          description: |
            A global unique voyage reference for the export Voyage, as per DCSA standard, agreed by VSA partners for the voyage. The voyage reference must match the regular expression pattern: `\d{2}[0-9A-Z]{2}[NEWSR]`
            
            - `2 digits` for the year
            - `2 alphanumeric characters` for the sequence number of the voyage
            - `1 character` for the direction/haul (`N`orth, `E`ast, `W`est, `S`outh or `R`oundtrip).
          example: 2103N
        carrierVoyages:
          type: array
          items:
            $ref: '#/components/schemas/CarrierVoyage'

    CarrierVoyage:
      type: object
      description: |
        An object including a carrier specific service code, service name, import- and export-voyageNumber and the SMDG code.
      properties:
        carrierSMDGCode:
          type: string
          maxLength: 10
          description: |
            The carrier code based on SMDG Liner Code List.
          example: MSK
        carrierServiceName:
          type: string
          maxLength: 50
          pattern: ^\S(?:.*\S)?$
          description: |
            The name of the service.
          example: Great Lion Service
        carrierServiceCode:
          type: string
          maxLength: 11
          pattern: ^\S(?:.*\S)?$
          description: |
            The carrier-specific code of the service for which the schedule details are published.
          example: FE1
        carrierImportVoyageNumber:
          type: string
          maxLength: 50
          pattern: ^\S(?:.*\S)?$
          description: |
            The identifier of an import voyage. The carrier-specific identifier of the import Voyage.

            **Condition:** It is mandatory to provide either `carrierImportVoyageNumber` or `carrierExportVoyageNumber` or both.
          example: 2103N
        carrierExportVoyageNumber:
          type: string
          maxLength: 50
          pattern: ^\S(?:.*\S)?$
          description: |
            The identifier of an export voyage. The carrier-specific identifier of the export Voyage.

            **Condition:** It is mandatory to provide either `carrierImportVoyageNumber` or `carrierExportVoyageNumber` or both.
          example: 2103S
      required:
        - carrierSMDGCode

    PartnerTransportCall:
      type: object
      description: |
        Lists universal service references and im/ex-portVoyages to carrier specific services, voyages and transportCalls.
      properties:
        universalServiceReference:
          type: string
          maxLength: 8
          minLength: 8
          pattern: ^SR\d{5}[A-Z]$
          description: |
            A global unique service reference, as per DCSA standard, agreed by VSA partners for the service. The service reference must match the regular expression pattern: `SR\d{5}[A-Z]`. The letters `SR` followed by `5` digits, followed by a checksum-character as a capital letter from `A to Z`.
          example: SR12345A
        universalImportVoyageReference:
          type: string
          minLength: 5
          maxLength: 5
          pattern: ^\d{2}[0-9A-Z]{2}[NEWSR]$
          description: |
            A global unique voyage reference for the import Voyage, as per DCSA standard, agreed by VSA partners for the voyage. The voyage reference must match the regular expression pattern: `\d{2}[0-9A-Z]{2}[NEWSR]`
            
            - `2 digits` for the year
            - `2 alphanumeric characters` for the sequence number of the voyage
            - `1 character` for the direction/haul (`N`orth, `E`ast, `W`est, `S`outh or `R`oundtrip).
          example: 2103N
        universalExportVoyageReference:
          type: string
          minLength: 5
          maxLength: 5
          pattern: ^\d{2}[0-9A-Z]{2}[NEWSR]$
          description: |
            A global unique voyage reference for the export Voyage, as per DCSA standard, agreed by VSA partners for the voyage. The voyage reference must match the regular expression pattern: `\d{2}[0-9A-Z]{2}[NEWSR]`
            
            - `2 digits` for the year
            - `2 alphanumeric characters` for the sequence number of the voyage
            - `1 character` for the direction/haul (`N`orth, `E`ast, `W`est, `S`outh or `R`oundtrip).
          example: 2103N
        carrierTransportCalls:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/CarrierTransportCall'

    CarrierTransportCall:
      type: object
      description: |
        An object including a carrier specific service code, service name, import- and export-voyageNumber, SMDG code and a list of transportCallReferences and their validity.
      properties:
        carrierSMDGCode:
          type: string
          maxLength: 10
          description: |
            The carrier code based on SMDG Liner Code List.
          example: MSK
        carrierServiceName:
          type: string
          maxLength: 50
          pattern: ^\S(?:.*\S)?$
          description: |
            The name of the service.
          example: Great Lion Service
        carrierServiceCode:
          type: string
          maxLength: 11
          pattern: ^\S(?:.*\S)?$
          description: |
            The carrier-specific code of the service for which the schedule details are published.
          example: FE1
        carrierImportVoyageNumber:
          type: string
          maxLength: 50
          pattern: ^\S(?:.*\S)?$
          description: |
            The identifier of an import voyage. The carrier-specific identifier of the import Voyage.
          example: 2103N
        carrierExportVoyageNumber:
          type: string
          maxLength: 50
          pattern: ^\S(?:.*\S)?$
          description: |
            The identifier of an export voyage. The carrier-specific identifier of the export Voyage.
          example: 2103S
        transportCallReferences:
          type: array
          minItems: 1
          description: |
            In case a carrier has multiple `transportCallReferences` for the same TransportCall - this property will contain more than one object.
          items:
            $ref: '#/components/schemas/TransportCallReference'
      required:
        - carrierSMDGCode
        - transportCallReferences
    TransportCallReference:
      type: object
      description: |
        This object indicates until when a `transportCallReference` is valid. If there is no `validUntilDateTime` present - it means that the value of the `transportCallReference` is the current valid reference.
      properties:
        transportCallReference:
          type: string
          maxLength: 100
          description: |
            The unique reference for the arrival transport call. It's the vessel operator's responsibility to provide the Transport Call Reference, other parties are obliged to pick it up and use it. It can take the form of Port Call References as defined in the OVS Definitions Document, or alternatively a reference as defined by the vessel operator.
          example: SR11111X-9321483-2107W-NLAMS-ACT-1-1
        validUntilDateTime:
          type: string
          format: date-time
          description: |
            If present, defines until when the `transportCallReference` is valid.
      required:
        - transportCallReference
