# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.3

#######################
# Optional info section
#######################

info:
  title: DCSA - Electronic Bill of Lading (EBL) Components
  description: Common components for DCSA APIs
  version: '1.0.0'

components:
  schemas:
  
    ######################################
    # Shipping Instruction Related objects
    ######################################
  
    shippingInstructionHeaderNoID:
      description: 'an enrichment to the original booking shared by the shipper to the carrier. The shipping instruction includes volume or weight, cargo items, shipping dates, origin, destination, and other special instructions. The information given by the shipper through the shipping instruction is the information required to create a Transport Document.'
      type: object
      allOf:
        - type: object
          properties:
            transportDocumentType:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/transportDocumentType'
        - type: object
          properties:
            isShippedOnboardType:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/isShippedOnboardType'
        - type: object
          properties:
            numberOfCopies:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/numberOfCopies'
        - type: object
          properties:
            numberOfOriginals:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/numberOfOriginals'
        - type: object
          properties:
            freightPayableAt:
              $ref: '#/components/schemas/location'
        # Extending freightPayableAt in order to alter example and description
        - type: object
          properties:
            freightPayableAt:
              description: 'A location object - here with an example with only UN location code and City name present'
              example:
                locationID: '123e4567-e89b-12d3-a456-426614174000'
                UNLocationCode: 'USNYC'
                address:
                  cityName: 'København'
                  stateRegion: 'N/A'
                  country: 'Denmark'
        - type: object
          properties:
            isElectronic:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/isElectronic'
        - type: object
          properties:
            carrierBookingReference:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/carrierBookingReference'
        # Extend the carrierBookingReference description for SI
        - type: object
          properties:
            carrierBookingReference:
              description: 'The associated booking number provided by the carrier. Cannot be used in combination with Cargo Item level carrierBookingReference'
        - type: object
          properties:
            callbackUrl:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/callbackUrl'
    
    shippingInstructionHeaderNoDS:
      description: 'an enrichment to the original booking shared by the shipper to the carrier. The shipping instruction includes volume or weight, cargo items, shipping dates, origin, destination, and other special instructions. The information given by the shipper through the shipping instruction is the information required to create a Transport Document.'
      type: object
      allOf:
        - type: object
          properties:
            shippingInstructionID:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/shippingInstructionID'
        - $ref: '#/components/schemas/shippingInstructionHeaderNoID'
      required:
        - shippingInstructionID

    shippingInstructionHeader:
      description: 'an enrichment to the original booking shared by the shipper to the carrier. The shipping instruction includes volume or weight, cargo items, shipping dates, origin, destination, and other special instructions. The information given by the shipper through the shipping instruction is the information required to create a Transport Document.'
      type: object
      allOf:
        - type: object
          properties:
            shippingInstructionID:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/shippingInstructionID'
        - type: object
          properties:
            documentStatus:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/documentStatus'
        - $ref: '#/components/schemas/shippingInstructionHeaderNoID'
      required:
        - shippingInstructionID
        - documentStatus

    shippingInstructionNoID:
      description: 'an enrichment to the original booking shared by the shipper to the carrier. The shipping instruction includes volume or weight, cargo items, shipping dates, origin, destination, and other special instructions. The information given by the shipper through the shipping instruction is the information required to create a Transport Document.'
      type: object
      allOf:
        - $ref: '#/components/schemas/shippingInstructionHeaderNoID'
        - $ref: '#/components/schemas/cargoItemList'
        - $ref: '#/components/schemas/shipmentEquipmentList'
        - $ref: '#/components/schemas/documentPartyList'
        - $ref: '#/components/schemas/referenceList'
      required:
        - transportDocumentType
        - isElectronic
        - callbackUrl

    shippingInstructionNoDS:
      description: 'The Shipping Instruction is an enrichment to the original booking shared by the shipper to the carrier. The shipping instruction includes volume or weight, cargo items, shipping dates, origin, destination, and other special instructions. The information given by the shipper through the shipping instruction is the information required to create a Transport Document.'
      type: object
      allOf:
        - $ref: '#/components/schemas/shippingInstructionHeaderNoDS'
        - $ref: '#/components/schemas/cargoItemList'
        - $ref: '#/components/schemas/shipmentEquipmentList'
        - $ref: '#/components/schemas/documentPartyList'
        - $ref: '#/components/schemas/referenceList'
      required:
        - callbackUrl
        
    shippingInstruction:
      description: 'The Shipping Instruction is an enrichment to the original booking shared by the shipper to the carrier. The shipping instruction includes volume or weight, cargo items, shipping dates, origin, destination, and other special instructions. The information given by the shipper through the shipping instruction is the information required to create a Transport Document.'
      type: object
      allOf:
        - $ref: '#/components/schemas/shippingInstructionHeader'
        - $ref: '#/components/schemas/cargoItemList'
        - $ref: '#/components/schemas/shipmentEquipmentList'
        - $ref: '#/components/schemas/documentPartyList'
        - $ref: '#/components/schemas/referenceList'
      required:
        - callbackUrl
  
    ############################
    # Cargo Item Related objects
    ############################
  
    cargoItemList:
      type: object
      properties:
        cargoItems:
          type: array
          items:
            $ref: '#/components/schemas/cargoItem'

    cargoItem:
      type: object
      allOf:
        - $ref: '#/components/schemas/cargoLineItems'
        - type: object
          properties:
            carrierBookingReference:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/carrierBookingReference'
        # Extend the carrierBookingReference description for CargoItem
        - type: object
          properties:
            carrierBookingReference:
              description: 'The associated booking number provided by the carrier for this cargo item. Cannot be used in combination with Shipping Instruction header level carrierBookingReference'

        - type: object
          properties:
            descriptionOfGoods:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/descriptionOfGoods'
        - type: object
          properties:
            HSCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/HSCode'
        - type: object
          properties:
            weight:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/weight'
        - type: object
          properties:
            volume:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/volume'
        - type: object
          properties:
            weightUnit:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/weightUnit'
        - type: object
          properties:
            volumeUnit:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/volumeUnit'
        - type: object
          properties:
            numberOfPackages:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/numberOfPackages'
        - type: object
          properties:
            packageCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/packageCode'
        - type: object
          properties:
            equipmentReference:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/equipmentReference'
      required:
        - descriptionOfGoods
        - HSCode
        - numberOfPackages
        - weight
        - weightUnit
        - packageCode
        - equipmentReference
      
    #################################
    # Cargo Line Item Related objects
    #################################

    cargoLineItems:
      type: object
      properties:
        cargoLineItems:
          type: array
          items:
            $ref: '#/components/schemas/cargoLineItem'
    cargoLineItem:
      type: object
      allOf:
        - type: object
          properties:
            cargoLineItemID:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/cargoLineItemID'
        - type: object
          properties:
            shippingMarks:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/shippingMarks'
      required:
        - cargoLineItemID
        - shippingMarks

    ####################################
    # Shipment Equipment Related objects
    ####################################

    shipmentEquipmentList:
      type: object
      properties:
        shipmentEquipments:
          type: array
          items:
            $ref: '#/components/schemas/shipmentEquipment'

    shipmentEquipment:
      type: object
      allOf:
        - type: object
          properties:
            equipment:
              $ref: '#/components/schemas/equipment'
        - type: object
          properties:
            weightUnit:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/weightUnit'
        - type: object
          properties:
            cargoGrossWeight:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/cargoGrossWeight'
        - type: object
          properties:
            activeReeferSettings:
              type: object
              description: specifies the settings for an active reefer container used to a shipment.
              allOf:
                - type: object
                  properties:
                    temperatureMin:
                      $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/temperatureMin'
                - type: object
                  properties:
                    temperatureMax:
                      $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/temperatureMax'
                - type: object
                  properties:
                    temperatureUnit:
                      $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/temperatureUnit'
                - type: object
                  properties:
                    humidityMin:
                      $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/humidityMin'
                - type: object
                  properties:
                    humidityMax:
                      $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/humidityMax'
                - type: object
                  properties:
                    ventilationMin:
                      $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/ventilationMin'
                - type: object
                  properties:
                    ventilationMax:
                      $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/ventilationMax'
        - $ref: '#/components/schemas/sealList'
      required:
        - weightUnit
        - cargoGrossWeight
        - equipment

    ######################
    # Seal Related objects
    ######################

    sealList:
      type: object
      properties:
        seals:
          type: array
          items:
            $ref: '#/components/schemas/seal'
    seal:
      type: object
      description: 'addresses the seal-related information associated with the shipment equipment. A seal is put on a shipment equipment once it is loaded. This seal is meant to stay on until the shipment equipment reaches its final destination.'
      allOf:
        - type: object
          properties:
            sealNumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/sealNumber'
        - type: object
          properties:
            sealSource:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/sealSource'
        - type: object
          properties:
            sealType:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/sealType'
      required:
        - sealNumber
        - sealType

    ################################
    # Document Party Related objects
    ################################

    documentPartyList:
      type: object
      properties:
        documentParties:
          type: array
          items:
            $ref: '#/components/schemas/documentParty'
    
    documentParty:
      description: stores the parties involved in the transport document.
      type: object
      allOf:
        - type: object
          properties:
            party:
              $ref: '#/components/schemas/party'
        - type: object
          properties:
            partyFunction:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/partyFunction'
        - type: object
          properties:
            displayedAddress:
              type: array
              items:
                $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/addressLine'
        - type: object
          properties:
            partyContactDetails:
              type: object
              allOf:
                - type: object
                  properties:
                    name:
                      $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/name'
                - type: object
                  properties:
                    phone:
                      $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/phone'
                - type: object
                  properties:
                    email:
                      $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/email'
                - type: object
                  properties:
                    fax:
                      $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/fax'
        - type: object
          properties:
            shouldBeNotified:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/shouldBeNotified'
      required:
        - partyFunction
        - shouldBeNotified

    #######################
    # Party Related objects
    #######################
  
    partyNoID:
      description: 'refers to a company or a legal entity.'
      type: object
      allOf:
        - type: object
          properties:
            partyName:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/partyName'
        - type: object
          properties:
            taxReference1:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/taxReference1'
        - type: object
          properties:
            taxReference2:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/taxReference2'
        - type: object
          properties:
            publicKey:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/publicKey'
        - type: object
          properties:
            address:
              allOf:
                - $ref: '#/components/schemas/address'
        - type: object
          properties:
            nmftaCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/nmftaCode'

    party:
      description: 'refers to a company or a legal entity.'
      type: object
      allOf:
        - type: object
          properties:
            partyID:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/partyID'
        - $ref: '#/components/schemas/partyNoID'

    ###################################
    # Shipment Location Related objects
    ###################################
  
    shipmentLocationList:
      type: object
      properties:
        shipmentLocations:
          type: array
          items:
            $ref: '#/components/schemas/shipmentLocation'
    
    shipmentLocationNoLocationType:
      type: object
      allOf:
        - type: object
          properties:
            location:
              allOf:
                - $ref: '#/components/schemas/location'
        - type: object
          properties:
            displayedName:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/displayedName'

    shipmentLocationNoLocationTypeExample:
      allOf:
        - $ref: '#/components/schemas/shipmentLocationNoLocationType'
      example:
        location:
          UNLocationCode: "USNYC"
        displayedName: "Kvædevej 55"
    shipmentLocationNoLocationTypeExample2:
      allOf:
        - $ref: '#/components/schemas/shipmentLocationNoLocationType'
      example:
        location:
          UNLocationCode: "NLRTM"
        displayedName: "Rotterdam"
    shipmentLocationNoLocationTypeExample3:
      allOf:
        - $ref: '#/components/schemas/shipmentLocationNoLocationType'
      example:
        location:
          UNLocationCode: "DEDUS"
        displayedName: "Düsseldorf"
      
    shipmentLocation:
      type: object
      description: 'maps the relationship between Shipment and Location, e.g., the place of receipt and the places of delivery for a specific shipment.'
      allOf:
        - $ref: '#/components/schemas/shipmentLocationNoLocationType'
        - type: object
          properties:
            locationType:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/locationType'
      required:
        - locationType

    ###########################
    # Reference Related objects
    ###########################
  
    referenceList:
      type: object
      properties:
        references:
          type: array
          items:
            $ref: '#/components/schemas/reference'
    reference:
      type: object
      allOf:
        - type: object
          properties:
            referenceType:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/referenceType'
        - type: object
          properties:
            referenceValue:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/referenceValue'
      required:
        - referenceType
        - referenceValue

    ####################################
    # Transport Document Related objects
    ####################################
  
    transportDocumentHeader:
      type: object
      allOf:
        - type: object
          properties:
            transportDocumentID:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/transportDocumentID'
        - type: object
          properties:
            placeOfIssue:
              $ref: '#/components/schemas/shipmentLocationNoLocationTypeExample'
        - type: object
          properties:
            dateOfIssue:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/dateOfIssue'
        - type: object
          properties:
            onboardDate:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/onboardDate'
        - type: object
          properties:
            receivedForShipmentDate:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/receivedForShipmentDate'
        - type: object
          properties:
            documentReferenceNumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/documentReferenceNumber'
        - type: object
          properties:
            termsAndConditions:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/termsAndConditions'
        - type: object
          properties:
            issuer:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/issuer'
        - type: object
          properties:
            declaredValueCurrency:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/declaredValueCurrency'
        - type: object
          properties:
            declaredValue:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/declaredValue'
        - type: object
          properties:
            numberOfRiderPages:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/numberOfRiderPages'
        - type: object
          properties:
            shipmentTermAtOrigin:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/shipmentTermAtOrigin'
        - type: object
          properties:
            shipmentTermAtDestination:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/shipmentTermAtDestination'
        - type: object
          properties:
            serviceTypeAtOrigin:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/serviceTypeAtOrigin'
        - type: object
          properties:
            serviceTypeAtDestination:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/serviceTypeAtDestination'
        - type: object
          properties:
            serviceContract:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/serviceContract'
      required:
        - transportDocumentID
        - shippingInstructionID
        - documentReferenceNumber
        - termsAndConditions
        - serviceTypeAtOrigin
        - serviceTypeAtDestination
        - shipmentTermAtOrigin
        - shipmentTermAtDestination
        - dateOfIssue
        - issuer
    transportDocument:
      type: object
      allOf:
        - $ref: '#/components/schemas/transportDocumentHeader'
        - type: object
          properties:
            shippingInstruction:
              allOf:
                - $ref: '#/components/schemas/shippingInstruction'
        - $ref: '#/components/schemas/chargeList'
        - $ref: '#/components/schemas/clauseList'
        - $ref: '#/components/schemas/transportPlan'

    ########################
    # Charge Related objects
    ########################

    chargeList:
      type: object
      properties:
        charges:
          type: array
          items:
            $ref: '#/components/schemas/charge'
  
    charge:
      type: object
      allOf:
        - type: object
          properties:
            chargeType:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/chargeType'
        - type: object
          properties:
            currencyAmount:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/currencyAmount'
        - type: object
          properties:
            currencyCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/currencyCode'
        - type: object
          properties:
            paymentTerm:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/paymentTerm'
        - type: object
          properties:
            calculationBasis:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/calculationBasis'
        - type: object
          properties:
            unitPrice:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/unitPrice'
        - type: object
          properties:
            quantity:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/quantity'
      required:
        - chargeType
        - currencyAmount
        - currencyCode
        - paymentTerm
        - calculationBasis
        - freightPayableAt
        - unitPrice
        - quantity

    ########################
    # Clause Related objects
    ########################

    clauseList:
      type: object
      properties:
        clauses:
          type: array
          items:
            $ref: '#/components/schemas/clause'
  
    clause:
      type: object
      allOf:
        - type: object
          properties:
            clauseContent:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/clauseContent'

    ######################
    # TransportPlan object
    ######################

    transportPlan:
      type: object
      properties:
        transportPlan:
          type: object
          allOf:
            - $ref: '#/components/schemas/shipmentLocationList'
            - $ref: '#/components/schemas/transportList'

    ###########################
    # Transport Related objects
    ###########################

    transportList:
      type: object
      properties:
        transports:
          type: array
          items:
            $ref: '#/components/schemas/transport'
  
    transport:
      type: object
      description: 'A list of transports sorted by ShipmentTransport sequenceNumber'
      allOf:
        - type: object
          properties:
            loadLocation:
              $ref: '#/components/schemas/shipmentLocationNoLocationTypeExample2'
        - type: object
          properties:
            dischargeLocation:
              $ref: '#/components/schemas/shipmentLocationNoLocationTypeExample3'
        - type: object
          properties:
            modeOfTransport:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/modeOfTransportCode'
        - type: object
          properties:
            vesselIMONumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/vesselIMONumber'
        - type: object
          properties:
            carrierVoyageNumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/carrierVoyageNumber'
        - type: object
          properties:
            isUnderShippersResponsibility:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/isUnderShippersResponsibility'

    ###########################
    # Equipment Related objects
    ###########################
  
    equipment:
      type: object
      allOf:
        - type: object
          properties:
            equipmentReference:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/equipmentReference'
        - type: object
          properties:
            ISOEquipmentCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/ISOEquipmentCode'
        - type: object
          properties:
            tareWeight:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/tareWeight'
        - type: object
          properties:
            weightUnit:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/weightUnit'
        - type: object
          properties:
            isShipperOwned:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/isShipperOwned'
      required:
        - equipmentReference

    ##########################
    # Location Related objects
    ##########################
  
    location:
      type: object
      description: 'generally used to capture location-related data, also for locations without UN Location Codes.'
      allOf:
        - type: object
          properties:
            locationID:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/locationID'
        - type: object
          properties:
            locationName:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/locationName'
        - type: object
          properties:
            latitude:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/latitude'
        - type: object
          properties:
            longitude:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/longitude'
        - type: object
          properties:
            UNLocationCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/UNLocationCode'
        - type: object
          properties:
            address:
              description: 'Address related information'
              allOf:
                - $ref: '#/components/schemas/address'

    address:
      type: object
      description: 'An object for storing address related information'
      allOf:
        - type: object
          properties:
            name:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/addressName'
        - type: object
          properties:
            streetName:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/streetName'
        - type: object
          properties:
            streetNumber:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/streetNumber'
        - type: object
          properties:
            floor:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/floor'
        - type: object
          properties:
            postalCode:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/postalCode'
        - type: object
          properties:
            cityName:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/cityName'
        - type: object
          properties:
            stateRegion:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/stateRegion'
        - type: object
          properties:
            country:
              $ref: 'https://api.swaggerhub.com/domains/dcsaorg/DCSA_DOMAIN/1.0.0#/components/schemas/country'
